quarkus.http.port=8081

# configure your datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234567
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/exchange

# para eliminar la bd en caso ya existe y la nuevamente para empezar de cero
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.openapi-generator.codegen.spec.api-proxy.base-package=org.mf.connector
quarkus.rest-client.api-proxy.url=https://free.e-api.net.pe/tipo-cambio
quarkus.rest-client.api-proxy.connect-timeout=5000
quarkus.rest-client.api-proxy.read-timeout=5000

quarkus.tls.trust-all=true

#Configuration level logging
quarkus.log.level=INFO

#configuration formatt out
quarkus.log.console.json=false
quarkus.log.console.enable=true
quarkus.log.console.color=true
