openapi: 3.0.2
info:
  title: Swagger Exchange API - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.27-SNAPSHOT
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
tags:
  - name: exchage
    description: Getting exchange of day
    externalDocs:
      description: Find out more
      url: https://swagger.io
paths:
  /exchange:
    post:
      tags:
        - exchange
      summary: Get exchange rate
      description: Get exchange rate with DNI
      operationId: getExchangeWithDni
      requestBody:
        description: Get exchange rate with DNI
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRate'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
      security:
        - petstore_auth:
            - write:pets
            - read:pets

components:
  schemas:
    ExchangeRate:
      type: object
      properties:
        dateToday:
          type: string
          format: date
          example: 11/08/2025
        exchangeRateSunat:
          type: number
          example: 3.70
        buy:
          type: number
          example: 3.70
        sell:
          type: number
          example: 3.70
    Person:
      type: object
      properties:
        dni:
          type: string
          example: 45895877
  requestBodies:
    Person:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Person'
