openapi: 3.0.2
info:
  title: Swagger Exchange API - OpenAPI 3.0
  description: |-
    This is a API for ABC Bank, which needs to add a feature to its mobile application a feature that allows users to consult exchange rates only with DNI information. Each DNI can make up to 10 inquiries per day.
  version: 1.0.0-SNAPSHOT
tags:
  - name: exchage
    description: Getting exchange of day
    externalDocs:
      description: Find out more
      url: https://swagger.io
paths:
  /exchange/{dni}:
    get:
      tags:
        - exchange
      summary: Getting exchange by DNI
      description: Getting exchange by DNI
      operationId: getExchangeByDni
      parameters:
        - name: dni
          in: path
          description: ID of person
          required: true
          schema:
            type: string
            example: "45986988"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRate'
        '400':
          description: invalid DNI
        '404':
          description: Maxim limit enquiry at day is 10
        default:
          description: Unexpected error
  /transactions:
    get:
      tags:
        - transaction
      summary: Getting transactions
      description: Getting transactions
      operationId: getTransactions
      responses:
        '200':
          description: succesful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
    post:
      tags:
        - transaction
      summary: Create a transaction
      description: Create a transaction
      operationId: createTransaction
      requestBody:
        description: Create a new transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /api/transactions:
    get:
      tags:
        - transactions
      summary: Search transactions por coincidencia semántica
      description: Busca transacciones relacionadas con una empresa inferida mediante Azure OpenAI.
      parameters:
        - name: word
          in: query
          required: true
          description: Palabra para realizar la inferencia semántica
          schema:
            type: string
      responses:
        '200':
          description: Lista de transacciones relacionadas con la empresa inferida.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Parámetro de consulta 'word' es requerido
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: No se encontró coincidencia semántica o transacciones relacionadas.
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    ExchangeRate:
      type: object
      properties:
        dateToday:
          type: string
          format: date
          example: 11/08/2025
        exchangeRateSunat:
          type: number
          example: 3.70
        buy:
          type: number
          example: 3.70
        sell:
          type: number
          example: 3.70
        message:
          type: string
        status:
          type: boolean
    Person:
      type: object
      properties:
        dni:
          type: string
          example: 45895877
    Transaction:
      type: object
      properties:
        id:
          type: string
          example: '654654654'
        companyName:
          type: string
          example: 'Repsol'
        description:
          type: string
          example: "Pago al grifo Repsol"
        amount:
          type: number
          format: double
          example: 50.00
  requestBodies:
    Person:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Person'
